runtime: aspnetcore
env: flex
service: default

instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  ASPNETCORE_URLS: "http://*:5011"
  GOOGLE_CLOUD_PROJECT: "hardy-pattern-451415-b8"

handlers:
- url: /.*
  script: auto
